name: inception

services:

  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception-net
    init: true

  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception-net
    init: true
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    ports: 
      - '443:443'   
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception-net
    depends_on:
      - wordpress

volumes:

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yachen/data/db
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yachen/data/wp

networks:

  inception-net:
    driver: bridge