services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    secrets:
      - credentials
      - db_password
      - db_root_password
    networks:
      - inception-net
    init: true
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/wordpress
    secrets:
      - credentials
      - db_password
    networks:
      - inception-net
    init: true
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - '443:443'   
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception-net
    init: true
    restart: on-failure
    depends_on:
      - wordpress

volumes:

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yachen/data/db
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yachen/data/wp

secrets:

  credentials:
    file: /home/user/inception/secrets/credentials.txt
  db_password:
    file: /home/user/inception/secrets/db_password.txt
  db_root_password:
    file: /home/user/inception/secrets/db_root_password.txt

networks:

  inception-net:
    driver: bridge